name: ECS Release

on:
  workflow_dispatch:
  release: 
    types: created

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: 744710710731.dkr.ecr.us-east-1.amazonaws.com/csi5112project
  ECS_SERVICE: csi5112projectService
  ECS_CLUSTER: csi5112project

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_ACCESS_KEY_SECRET }}
        aws-region: ${{ env.AWS_REGION }}
        
    - name: Docker build
      run: |
        aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin 744710710731.dkr.ecr.us-east-1.amazonaws.com
        docker build -t csi5112project .
        docker tag csi5112project:latest 744710710731.dkr.ecr.us-east-1.amazonaws.com/csi5112project:latest
        docker push 744710710731.dkr.ecr.us-east-1.amazonaws.com/csi5112project:latest
        aws ecs update-service --cluster $ECS_CLUSTER --service $ECS_SERVICE --force-new-deployment --region $AWS_REGION
